#!/usr/bin/env bash
#
#   - simple picture array maker -
#   Copyright (C) 2024  sumcodebit  -@github.com
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

# default values which correspond to
# ( tile corner border column row crop )
defaults=( 200 0 10 3 3 0 )
_self="$0"

showHelp() {
	cat <<EOH
simple picture array maker
Usage: $_self [-s VALUE] [-k VALUE] [-b VALUE] [-c VALUE] [-r VALUE] [-t] [-h] [DIRECTORY]
  if DIRECTORY is omitted, the current one will be used
  default values are in [...]

  -s   maximum tilesize in px  [${defaults[0]}]
  -k   corner radius in px  [${defaults[1]}]
  -b   border around each tile in px  [${defaults[2]}]
        (equates to half the gap between each tile)
  -c   amount of pictures horizontally (columns)  [${defaults[3]}]
  -r   amount of pictures vertically (rows)  [${defaults[4]}]
  -t   crop / trim non-squared pictures  [$( ((defaults[5])) && echo "yes" || echo "no" )]
  -h   show this help
EOH
}

# parse commandline options
while getopts ":s:k:b:c:r:th" option; do
	case $option in
		s)	_tilesize=$OPTARG ;;
		k)	_cornersize=$OPTARG ;;
		b)	_bordersize=$OPTARG ;;
		c)	_columns=$OPTARG ;;
		r)	_rows=$OPTARG ;;
		t)	_crop=1 ;;
		h)	showHelp ; exit 0 ;;
		?)	>&2 printf '%s\n' "Usage: $_self [-skbcr VALUE] [-th] [DIR]" \
				"use '$_self -h' for more help"
			exit 1 ;;
	esac
done

echoErr() {
	>&2 echo "$1"
	[ -n "$2" ] && cleanUp 1
	exit 1
}

cleanUp() {
# resets shell environment into pre-execution state
	[ -f "${outputdir}/mask.miff" ] && rm -f "${outputdir}/mask.miff" >/dev/null
	$GLOBIGNORE=$old_GLOBIGNORE
	(( set_nullglob )) && shopt -u nullglob
	[ "$1" == "1" ] && exit 1 || exit
}

testInt() {
# tests input for valid numbers
	case "${1-}" in
		*[^0-9]*)
			echoErr "$_self : optional parameter is not an integer" ;;
		*) : ;;
	esac
}

#set default values, if unset
for a in _tilesize _cornersize _bordersize _columns _rows _crop; do
	testInt "${!a}"
	: ${!a:=${defaults[${i=0}]}}
	(( i++ ))
done
tilesum=$(( _columns * _rows ))
unset -v i defaults

# check if null globbing was set, to set after `trap`
shopt -q nullglob; set_nullglob=$?

picdirarray=( $(readlink -m ${@:$OPTIND} 2>/dev/null) )
old_GLOBIGNORE=$GLOBIGNORE

trap cleanUp 1 2 3 6 15
GLOBIGNORE=.*:*.html:*.md:*.ini
(( set_nullglob )) && shopt -s nullglob

if [ -z "$picdirarray" ]; then
	picdirarray=( "$PWD" )
	echo "$_self : using current directory \"${picdirarray[0]}\""
	read -N 1 -p "continue operation? [y/N]" ask
	case $ask in
		y|Y) echo ;;
		*) echo; exit ;;
	esac
fi

createMask() {
# creates a mask for all pictures
	gm convert -size "${_tilesize}x${_tilesize}" \
		xc:white \
		-fill black \
		-draw "roundRectangle 0,0 ${_tilesize},${_tilesize} ${_cornersize},${_cornersize}" \
		"${outputdir}/mask.miff"
}

makeCrop() {
	gm convert -resize "${_tilesize}x${_tilesize}^" \
		"$pic" \
		-gravity center \
		-crop "${_tilesize}x${_tilesize}+0+0" \
		miff:-
}

makeNoCrop() {
	gm convert "$pic" \
		-resize "${_tilesize}x${_tilesize}" \
		-gravity center \
		-background "#d3d3d3" \
		-extent "${_tilesize}x${_tilesize}" \
		miff:-
}

makeMask() {
	gm convert -compose Plus \
		miff:- "${outputdir}/mask.miff" \
		-flatten miff:-
}

makeMontageStd() {
	gm montage -background white \
		-tile "${_columns}x${_rows}" \
		-geometry "+${_bordersize}+${_bordersize}" \
		miff:- miff:-
}

makeMontageSimple() {
	gm montage -background white \
		-tile "${_columns}x${_rows}" \
		-geometry "${_tilesize}x${_tilesize}+${_bordersize}+${_bordersize}" \
		"${picarray[@]:${offset}:${tilesum}}" \
		miff:-
}

makeOuterBorder() {
	gm convert -bordercolor white \
		-border "${_bordersize}x${_bordersize}" \
		miff:- "${outputdir}/montage_${i}.png"
}

createOutput() {
	picsum=${#picarray[@]}
	outsum=$(( (picsum + tilesum - 1) / tilesum ))
	offset=0
	for i in $(seq -w 1 $outsum); do

		if [[ $_cornersize -gt 0 ]] || [[ $_crop -eq 1 ]] ; then

			for pic in "${picarray[@]:${offset}:${tilesum}}"; do
				if [ $_crop -eq 1 ]; then
					[ $_cornersize -gt 0 ] && makeCrop | makeMask || makeCrop
				else
					makeNoCrop | makeMask
				fi
			done | makeMontageStd | makeOuterBorder

		else
			makeMontageSimple | makeOuterBorder
		fi
		offset=$(( offset + tilesum ))
	done
}

# iterate through every given directory
for picdir in "${picdirarray[@]}"; do
	cd "$picdir" 2>/dev/null ||
		echoErr "$_self : invalid directory \"$picdir\"" clean

	picarray=(*.*)
	[ -z "$picarray" ] &&
		echoErr "$_self : no pictures found in \"$picdir\"" clean

	outputdir="output_${_self##*/}_$(date '+%Y%m%d_%H%M%S')"
	mkdir "$outputdir" 2>/dev/null ||
		echoErr "$_self : failed to create output directory" clean

	[ $_cornersize -gt 0 ] && createMask
	echo "$_self : working on directory \"$picdir\""

	createOutput
	rm -f "${outputdir}/mask.miff" >/dev/null
done

cleanUp
